name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y nlohmann-json3-dev

      - name: Configure
        run: cmake -B build .

      - name: Build tests
        run: cmake --build build --target unit_tests

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
